/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package drawing.domain;
import java.io.File;
import java.util.Collections;
/**
 *
 * @author Maikkeyy
 */
public class StartGUI extends javax.swing.JFrame {

    private Drawing drawing;
    /**
     * Creates new form StartGUI
     */
    public StartGUI() {
        initComponents();
        drawing = new Drawing();
        
        Point point = new Point(5, 5);
        Oval oval = new Oval(Color.BLUE, point, 30, 30, 1);
        
        Point point2 = new Point(15, 15);
        Image image = new Image(Color.RED, point2, 100, 100, 
                new File("C:\\Users\\Maikkeyy\\Desktop\\School\\ICT\\Semester 3\\JCC\\Tekenapplicatie\\text.txt"));
        
        Point point3 = new Point(20, 20);
        PaintedText text = new PaintedText(Color.GREEN, point3, 100, 20, "Hallo", "Arial");
        
        Point point4 = new Point(2, 2);
        Polygon polygon = new Polygon(Color.GREEN, point4, 50, 50, new Point[5], 1);
        
        drawing.addItem(image);
        drawing.addItem(oval);
        drawing.addItem(text);
        drawing.addItem(polygon);
        
        Collections.sort(drawing.getItems(), new DistanceComparator());
        
        for(DrawingItem item : drawing.getItems()) {
            System.out.println(item.toString());
        }
        
       /* oval.setAnchor(new Point(40, 40));
        System.out.println(oval.toString());
        
        oval.revert();
        System.out.println(oval.toString());
        
        oval.setColor(Color.WHITE);
        System.out.println(oval.toString()); */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tbName = new javax.swing.JTextField();
        OKButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tekenapplicatie");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 255));
        jLabel1.setText("Welkom bij GraphiX!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 130, -1));

        jLabel2.setText("Naam:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        tbName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbNameActionPerformed(evt);
            }
        });
        getContentPane().add(tbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 120, -1));

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OKButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbNameActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_OKButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tbName;
    // End of variables declaration//GEN-END:variables
}
